id: I74E38BEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:22:50+00:00'
last_modified: '2022-06-07T13:40:57.315417+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27496
  title: བཤད་རྒྱུད་ཀྱི་འགྲེལ་ཆེན་བདུད་རྩིའི་ཆུ་རྒྱུན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2747':
      image_group_id: I4706
      title: ''
      total_pages: 758
      order: 1
      base_file: 2747.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
